{% set data = load_setup_py_data() %}

package:
  name: 'wgfast'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/wgfast

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - wgfast = wgfast.main:main

requirements:
  build:
    - python==3.6
    - setuptools
  run:
    - python==3.6
    - biopython
    - dendropy # -c bioconda
    - samtools # -c bioconda
    - bwa==0.7.8
    - java-1.7.0-openjdk-cos6-x86_64 # -c anaconda
    - java-jdk # -c anaconda

test:
  imports:
    - wgfast
   commands:
    - python -m unittest -v run_tests.py


