{% set data = load_setup_py_data() %}

package:
  name: 'wgfast'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/wgfast

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - wgfast = wgfast.main:main
    - wgfast_prep = wgfast.tools.wgfast_prep:main


requirements:
  build:
    - python==3.6
    - setuptools
  run:
    - python==3.6
    - biopython
    - dendropy # -c bioconda
    - samtools # -c bioconda
    - bwa==0.7.8
    - bbmap # -c bioconda
    - raxml # -c bioconda
    - picard # bioconda

test:
  imports:
    - wgfast
  commands:
    - wgfast --help > /dev/null



about:
  home: https://github.com/jasonsahl/wgfast
  summary: The whole genome focused array SNP typing (WG-FAST) pipeline