package:
  name: 'wgfast'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/wgfast

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"
  entry_points:
    - wgfast = wgfast.main:main
    - wgfast_prep = wgfast.tools.wgfast_prep:main
    - wgfastdb = wgfastdb.main:main
    - wgfast_genbankqc = genbankqc.__main__:cli


requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython
    - pandas
    - click
    - dendropy 
    - samtools 
    - bwa
    - bbmap
    - raxml 
    - picard 
    - mash
    - nasp 
    - ncbitk 
    - snakemake >=5 
    - logbook
    - qt
    - pathos 
    - ete3
    - retrying




test:
  commands:
    - wgfast --help
    - wgfast_prep --help
    - wgfastdb --help
    - wgfast_genbankqc --help

about:
  home: https://github.com/jasonsahl/wgfast
  summary: 'The whole genome focused array SNP typing (WG-FAST) pipeline'
  license: 'GPL v3'
  license_file: LICENSE
  license_family: 'GPL'

