package:
  name: 'wgfast'
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/FofanovLab/wgfast

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: true  # [not linux]
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - wgfast = wgfast.main:main
    - wgfast_prep = wgfast.tools.wgfast_prep:main
    - wgfastdb = wgfastdb.main:main


requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - biopython
    - dendropy # -c bioconda
    - samtools # -c bioconda
    - bwa==0.7.8
    - bbmap # -c bioconda
    - raxml # -c bioconda
    - picard # bioconda
    - mash # -c bioconda
    - nasp # -c bioconda
    - ncbitk # -c tara_furstenau
    - snakemake >=5 # -c bioconda
    - genbankqc # -c tara_furstenau


test:
  commands:
    - wgfast --help
    - wgfast_prep --help
    - wgfast_db --help

about:
  home: https://github.com/jasonsahl/wgfast
  summary: 'The whole genome focused array SNP typing (WG-FAST) pipeline'
  license: 'GPL v3'
  license_file: LICENSE
  license_family: 'GPL'

